In [2]:
import pandas as pd

In [3]:
df3 = pd.read_csv('./3. 2013년 이후 재무 데이터 (분기).csv')
df3

,코드,코드명,아이템명,2014-03-31 00:00:00,2014-06-30 00:00:00,2014-09-30 00:00:00,2014-12-30 00:00:00,2015-03-31 00:00:00,2015-06-30 00:00:00,2015-09-30 00:00:00,...,2024-03-29 00:00:00,2024-06-28 00:00:00,2024-09-30 00:00:00,2024-12-30 00:00:00,2025-03-31 00:00:00,2025-06-30 00:00:00,2025-09-30 00:00:00,2025-12-30 00:00:00,2026-03-31 00:00:00,2026-06-04 00:00:00
0,A005930,삼성전자,매출액(천원),5.367533e+10,5.235323e+10,4.744731e+10,5.273012e+10,4.711792e+10,4.853754e+10,5.168257e+10,...,7.191560e+10,7.406830e+10,7.909873e+10,7.578827e+10,7.914050e+10,7.456632e+10,8.606175e+10,9.383737e+10,1.338734e+11,NaN
1,A005930,삼성전자,영업이익(천원),8.488799e+09,7.187323e+09,4.060522e+09,5.288427e+09,5.979367e+09,6.897937e+09,7.393373e+09,...,6.606009e+09,1.044388e+10,9.183371e+09,6.492703e+09,6.685272e+09,4.676057e+09,1.216606e+10,2.007366e+10,5.723280e+10,NaN
2,A005930,삼성전자,세전계속사업이익(천원),9.648970e+09,7.785106e+09,4.846871e+09,5.594087e+09,6.218643e+09,7.628024e+09,7.390119e+09,...,7.706723e+09,1.159534e+10,1.032041e+10,7.907255e+09,9.151576e+09,5.756129e+09,1.354556e+10,2.102820e+10,5.882843e+10,NaN
3,A005930,삼성전자,당기순이익(지배)(천원),7.484680e+09,6.176506e+09,4.135422e+09,5.285891e+09,4.519323e+09,5.626734e+09,5.306104e+09,...,6.621030e+09,9.642653e+09,9.781547e+09,7.576133e+09,8.028407e+09,4.934034e+09,1.200646e+10,1.929205e+10,4.710119e+10,NaN
4,A005930,삼성전자,당기순이익(비지배)(천원),8.976100e+07,7.427500e+07,8.692300e+07,6.090000e+07,1.064920e+08,1.255630e+08,1.524550e+08,...,1.336780e+08,1.986920e+08,3.193570e+08,1.782610e+08,1.944710e+08,1.824010e+08,2.192860e+08,3.496910e+08,1.240820e+08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132272,A495900,에이엠시지,외국인지분율(%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN
132273,A495900,에이엠시지,총현금흐름(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132274,A495900,에이엠시지,CAPEX(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132275,A495900,에이엠시지,기초현금(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132276,A495900,에이엠시지,기말현금(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# wide -> long format transformation

data_columns = df3.columns[3:]
data_columns

Index(['2014-03-31 00:00:00', '2014-06-30 00:00:00', '2014-09-30 00:00:00',
       '2014-12-30 00:00:00', '2015-03-31 00:00:00', '2015-06-30 00:00:00',
       '2015-09-30 00:00:00', '2015-12-30 00:00:00', '2016-03-31 00:00:00',
       '2016-06-30 00:00:00', '2016-09-30 00:00:00', '2016-12-29 00:00:00',
       '2017-03-31 00:00:00', '2017-06-30 00:00:00', '2017-09-29 00:00:00',
       '2017-12-28 00:00:00', '2018-03-30 00:00:00', '2018-06-29 00:00:00',
       '2018-09-28 00:00:00', '2018-12-28 00:00:00', '2019-03-29 00:00:00',
       '2019-06-28 00:00:00', '2019-09-30 00:00:00', '2019-12-30 00:00:00',
       '2020-03-31 00:00:00', '2020-06-30 00:00:00', '2020-09-29 00:00:00',
       '2020-12-30 00:00:00', '2021-03-31 00:00:00', '2021-06-30 00:00:00',
       '2021-09-30 00:00:00', '2021-12-30 00:00:00', '2022-03-31 00:00:00',
       '2022-06-30 00:00:00', '2022-09-30 00:00:00', '2022-12-29 00:00:00',
       '2023-03-31 00:00:00', '2023-06-30 00:00:00', '2023-09-27 00:00:00',
       '2023-12-28 00:00:00', '2024-03-29 00:00:00', '2024-06-28 00:00:00',
       '2024-09-30 00:00:00', '2024-12-30 00:00:00', '2025-03-31 00:00:00',
       '2025-06-30 00:00:00', '2025-09-30 00:00:00', '2025-12-30 00:00:00',
       '2026-03-31 00:00:00', '2026-06-04 00:00:00'],
      dtype='str')

In [5]:
date_columns = df3.columns[3:]  # 코드, 코드명, 아이템명 제외

df_long = df3.melt(
    id_vars=['코드', '코드명', '아이템명'],
    value_vars=date_columns,
    var_name='날짜',
    value_name='값'
)
df_long['날짜'] = pd.to_datetime(df_long['날짜'])
df_long['연도'] = df_long['날짜'].dt.year
df_long['값'] = pd.to_numeric(df_long['값'], errors='coerce')

In [6]:
df_long

              코드    코드명            아이템명         날짜             값    연도
0        A005930   삼성전자         매출액(천원) 2014-03-31  5.367533e+10  2014
1        A005930   삼성전자        영업이익(천원) 2014-03-31  8.488799e+09  2014
2        A005930   삼성전자    세전계속사업이익(천원) 2014-03-31  9.648970e+09  2014
3        A005930   삼성전자   당기순이익(지배)(천원) 2014-03-31  7.484680e+09  2014
4        A005930   삼성전자  당기순이익(비지배)(천원) 2014-03-31  8.976100e+07  2014
...          ...    ...             ...        ...           ...   ...
6613845  A495900  에이엠시지       외국인지분율(%) 2026-06-04           NaN  2026
6613846  A495900  에이엠시지       총현금흐름(천원) 2026-06-04           NaN  2026
6613847  A495900  에이엠시지       CAPEX(천원) 2026-06-04           NaN  2026
6613848  A495900  에이엠시지        기초현금(천원) 2026-06-04           NaN  2026
6613849  A495900  에이엠시지        기말현금(천원) 2026-06-04           NaN  2026

[6613850 rows x 6 columns]

In [10]:
# 필요한 항목만 추출 (자본총계, 액면가, 기말발행주식수)

target_items = ['자본총계(천원)', '액면가(원,US센트)', '기말발행주식수(보통주)(주)']
sub_df = df_long[df_long['아이템명'].isin(target_items)]

In [12]:
# 각 연도의 '마지막 분기(연말)' 값만 선택

year_end = (
    sub_df.sort_values('날짜').groupby(['코드', '코드명', '아이템명', '연도']).last().reset_index()
)

In [13]:
year_end

             코드      코드명             아이템명    연도         날짜           값
0       A000010  (주)신한은행  기말발행주식수(보통주)(주)  2014 2014-12-30         0.0
1       A000010  (주)신한은행  기말발행주식수(보통주)(주)  2015 2015-12-30         0.0
2       A000010  (주)신한은행  기말발행주식수(보통주)(주)  2016 2016-12-29         0.0
3       A000010  (주)신한은행  기말발행주식수(보통주)(주)  2017 2017-12-28         0.0
4       A000010  (주)신한은행  기말발행주식수(보통주)(주)  2018 2018-12-28         0.0
...         ...      ...              ...   ...        ...         ...
166408  A950250      테라뷰         자본총계(천원)  2022 2022-12-29         NaN
166409  A950250      테라뷰         자본총계(천원)  2023 2023-12-28         NaN
166410  A950250      테라뷰         자본총계(천원)  2024 2024-12-30         NaN
166411  A950250      테라뷰         자본총계(천원)  2025 2025-12-30  35878462.0
166412  A950250      테라뷰         자본총계(천원)  2026 2026-06-04         NaN

[166413 rows x 6 columns]

In [15]:
# 아이템명을 컬럼으로 피벗 -> 새로운 테이블 짜기
pivot = year_end.pivot_table(index =['코드', '코드명', '연도'],
                             columns='아이템명',
                             values = '값').reset_index()
pivot.columns.name = None
pivot

            코드      코드명    연도  기말발행주식수(보통주)(주)  액면가(원,US센트)      자본총계(천원)
0      A000010  (주)신한은행  2014              0.0          NaN  2.047690e+10
1      A000010  (주)신한은행  2015              0.0          NaN  2.083935e+10
2      A000010  (주)신한은행  2016              0.0          NaN  2.146697e+10
3      A000010  (주)신한은행  2017              0.0          NaN  2.265286e+10
4      A000010  (주)신한은행  2018              0.0          NaN  2.419254e+10
...        ...      ...   ...              ...          ...           ...
55466  A950250      테라뷰  2022              0.0          NaN           NaN
55467  A950250      테라뷰  2023              0.0          NaN           NaN
55468  A950250      테라뷰  2024              0.0          NaN           NaN
55469  A950250      테라뷰  2025       35517731.0          0.0  3.587846e+07
55470  A950250      테라뷰  2026       35517731.0          0.0           NaN

[55471 rows x 6 columns]

In [17]:
# 자본금 계산
# 자본총계 -> 천원 단위, 액면가 -> 원 단위
# 자본금 = 액면가(원) x 발행주식수(주)
# 차본금(천원) = 자본금(원) / 1000
pivot['자본금(천원)'] = pivot['액면가(원,US센트)'] * pivot['기말발행주식수(보통주)(주)'] /1000
pivot

,코드,코드명,연도,기말발행주식수(보통주)(주),"액면가(원,US센트)",자본총계(천원),자본금(천원)
0,A000010,(주)신한은행,2014,0.0,NaN,2.047690e+10,NaN
1,A000010,(주)신한은행,2015,0.0,NaN,2.083935e+10,NaN
2,A000010,(주)신한은행,2016,0.0,NaN,2.146697e+10,NaN
3,A000010,(주)신한은행,2017,0.0,NaN,2.265286e+10,NaN
4,A000010,(주)신한은행,2018,0.0,NaN,2.419254e+10,NaN
...,...,...,...,...,...,...,...
55466,A950250,테라뷰,2022,0.0,NaN,NaN,NaN
55467,A950250,테라뷰,2023,0.0,NaN,NaN,NaN
55468,A950250,테라뷰,2024,0.0,NaN,NaN,NaN
55469,A950250,테라뷰,2025,35517731.0,0.0,3.587846e+07,0.0
55470,A950250,테라뷰,2026,35517731.0,0.0,NaN,0.0

In [28]:
# 부실 의심 플래그
# 자본잠식률 50% 이상
pivot['자본잠식률(%)'] = (pivot['자본금(천원)']-pivot['자본총계(천원)'])/pivot['자본금(천원)'] * 100
pivot['관리종목의심(50%이상)'] = pivot['자본잠식률(%)'] >= 50
pivot['완전자본잠식'] = pivot['자본총계(천원)'] <= 0
pivot

,코드,코드명,연도,기말발행주식수(보통주)(주),"액면가(원,US센트)",자본총계(천원),자본금(천원),자본잠식률(%),관리종목의심(50%이상,완전자본잠식,관리종목의심(50%이상)
0,A000010,(주)신한은행,2014,0.0,NaN,2.047690e+10,NaN,NaN,False,False,False
1,A000010,(주)신한은행,2015,0.0,NaN,2.083935e+10,NaN,NaN,False,False,False
2,A000010,(주)신한은행,2016,0.0,NaN,2.146697e+10,NaN,NaN,False,False,False
3,A000010,(주)신한은행,2017,0.0,NaN,2.265286e+10,NaN,NaN,False,False,False
4,A000010,(주)신한은행,2018,0.0,NaN,2.419254e+10,NaN,NaN,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
55466,A950250,테라뷰,2022,0.0,NaN,NaN,NaN,NaN,False,False,False
55467,A950250,테라뷰,2023,0.0,NaN,NaN,NaN,NaN,False,False,False
55468,A950250,테라뷰,2024,0.0,NaN,NaN,NaN,NaN,False,False,False
55469,A950250,테라뷰,2025,35517731.0,0.0,3.587846e+07,0.0,-inf,False,False,False
55470,A950250,테라뷰,2026,35517731.0,0.0,NaN,0.0,NaN,False,False,False

In [29]:
result = pivot.sort_values(['코드명', '연도'])

In [30]:
result

,코드,코드명,연도,기말발행주식수(보통주)(주),"액면가(원,US센트)",자본총계(천원),자본금(천원),자본잠식률(%),관리종목의심(50%이상,완전자본잠식,관리종목의심(50%이상)
2769,A002550,(주)KB손해보험,2014,60000000.0,500.0,1.784852e+09,30000000.0,-5849.506876,False,False,False
2770,A002550,(주)KB손해보험,2015,60000000.0,500.0,2.111240e+09,30000000.0,-6937.466446,False,False,False
2771,A002550,(주)KB손해보험,2016,66500000.0,500.0,2.447465e+09,33250000.0,-7260.798112,False,False,False
2772,A002550,(주)KB손해보험,2017,0.0,500.0,2.497243e+09,0.0,-inf,False,False,False
2773,A002550,(주)KB손해보험,2018,0.0,NaN,NaN,NaN,NaN,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
42804,A238490,힘스,2022,11312236.0,500.0,6.193453e+07,5656118.0,-995.000758,False,False,False
42805,A238490,힘스,2023,11312236.0,500.0,6.853113e+07,5656118.0,-1111.628335,False,False,False
42806,A238490,힘스,2024,11312236.0,500.0,7.068693e+07,5656118.0,-1149.742768,False,False,False
42807,A238490,힘스,2025,11312236.0,500.0,5.816199e+07,5656118.0,-928.302238,False,False,False
42808,A238490,힘스,2026,11312236.0,500.0,5.706581e+07,5656118.0,-908.921767,False,False,False

In [31]:
pivot = pivot.sort_values(['코드', '연도']).reset_index(drop=True)

In [32]:
pivot

,코드,코드명,연도,기말발행주식수(보통주)(주),"액면가(원,US센트)",자본총계(천원),자본금(천원),자본잠식률(%),관리종목의심(50%이상,완전자본잠식,관리종목의심(50%이상)
0,A000010,(주)신한은행,2014,0.0,NaN,2.047690e+10,NaN,NaN,False,False,False
1,A000010,(주)신한은행,2015,0.0,NaN,2.083935e+10,NaN,NaN,False,False,False
2,A000010,(주)신한은행,2016,0.0,NaN,2.146697e+10,NaN,NaN,False,False,False
3,A000010,(주)신한은행,2017,0.0,NaN,2.265286e+10,NaN,NaN,False,False,False
4,A000010,(주)신한은행,2018,0.0,NaN,2.419254e+10,NaN,NaN,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
55466,A950250,테라뷰,2022,0.0,NaN,NaN,NaN,NaN,False,False,False
55467,A950250,테라뷰,2023,0.0,NaN,NaN,NaN,NaN,False,False,False
55468,A950250,테라뷰,2024,0.0,NaN,NaN,NaN,NaN,False,False,False
55469,A950250,테라뷰,2025,35517731.0,0.0,3.587846e+07,0.0,-inf,False,False,False
55470,A950250,테라뷰,2026,35517731.0,0.0,NaN,0.0,NaN,False,False,False

In [35]:
# ============================================
# 1. 연도 순으로 정렬 (rolling 계산 전 필수)
# ============================================
pivot = pivot.sort_values(['코드', '연도']).reset_index(drop=True)

# ============================================
# 2. 종목별로 "관리종목의심"이 2년 연속 True인지 체크
# ============================================
pivot['부실기업_2년연속'] = (
    pivot.groupby('코드')['관리종목의심(50%이상)']
    .transform(lambda x: x.rolling(window=2, min_periods=2).sum() == 2)
)

In [40]:
company_status =(
    pivot.groupby(['코드', '코드명'])['부실기업_2년연속']
                   .any()
                   .reset_index()
                   .rename(columns = {'부실기업_2년연속' : '부실기업_여부'})
    )

In [38]:
company_status = (
    pivot.groupby(['코드', '코드명'])['부실기업_2년연속']
    .any()  # 어느 연도에서든 한 번이라도 True면 그 종목은 부실기업으로 분류
    .reset_index()
    .rename(columns={'부실기업_2년연속': '부실기업_여부'})
)

In [41]:
company_status

           코드         코드명  부실기업_여부
0     A000010     (주)신한은행    False
1     A000020        동화약품    False
2     A000030     (주)우리은행    False
3     A000040       KR모터스    False
4     A000050          경방    False
...       ...         ...      ...
4262  A950190     고스트스튜디오    False
4263  A950200         소마젠    False
4264  A950210  프레스티지바이오파마    False
4265  A950220       네오이뮨텍    False
4266  A950250         테라뷰    False

[4267 rows x 3 columns]

In [42]:
target_items = [
    '부채총계(천원)', '자본총계(천원)', '영업이익(천원)',
    '영업활동으로인한현금흐름(천원)', '당기순이익(천원)', '유동자산(천원)',
    '자산총계(천원)', '이익잉여금(천원)', '매출액(천원)',
    '시가총액(티커-상장예정주식수 포함)(백만원)'
]

In [43]:

missing = [item for item in target_items if item not in df_long['아이템명'].unique()]
if missing:
    print(f"⚠️ STEP 2 - 데이터에 없는 아이템명: {missing}")
else:
    print("✅ STEP 2 - 모든 아이템명 확인 완료")

✅ STEP 2 - 모든 아이템명 확인 완료

In [44]:
# 분기별 재무 데이터 추출
sub_df = df_long[df_long['아이템명'].isin(target_items)].copy()

In [46]:
quarter_pivot = sub_df.pivot_table(index = ['코드', '코드명', '날짜'],
                                   columns= '아이템명', values='값', aggfunc ='first').reset_index()
quarter_pivot

아이템명,코드,코드명,날짜,당기순이익(천원),매출액(천원),부채총계(천원),시가총액(티커-상장예정주식수 포함)(백만원),영업이익(천원),영업활동으로인한현금흐름(천원),유동자산(천원),이익잉여금(천원),자본총계(천원),자산총계(천원)
0,A000010,(주)신한은행,2014-03-31,425157000.0,3.266976e+09,2.218657e+11,NaN,533673000.0,-2.771267e+09,NaN,9.838993e+09,2.056530e+10,2.424310e+11
1,A000010,(주)신한은행,2014-06-30,416954000.0,3.703068e+09,2.259672e+11,NaN,509186000.0,1.194104e+09,NaN,1.022730e+10,1.989330e+10,2.458605e+11
2,A000010,(주)신한은행,2014-09-30,430192000.0,2.980610e+09,2.320100e+11,NaN,548536000.0,-8.306920e+08,NaN,1.064001e+10,2.040162e+10,2.524117e+11
3,A000010,(주)신한은행,2014-12-30,183350000.0,3.418039e+09,2.351694e+11,NaN,206001000.0,6.221510e+08,NaN,1.080557e+10,2.047690e+10,2.556463e+11
4,A000010,(주)신한은행,2015-03-31,390022000.0,3.257967e+09,2.407635e+11,NaN,468606000.0,-1.522832e+09,NaN,1.072814e+10,2.009479e+10,2.608583e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
125966,A950250,테라뷰,2025-06-30,-1463047.0,1.884841e+06,8.031245e+06,NaN,-1556428.0,-5.686100e+05,8219631.0,-1.174321e+08,1.266033e+06,9.297279e+06
125967,A950250,테라뷰,2025-09-30,-1284777.0,1.458068e+06,9.053882e+06,NaN,-1976867.0,-1.152912e+06,8012532.0,-1.212469e+08,6.901000e+03,9.060783e+06
125968,A950250,테라뷰,2025-12-30,-3212680.0,2.409468e+06,9.700868e+06,267448.51,-2540414.0,-3.235584e+06,44608231.0,-1.309612e+08,3.587846e+07,4.557933e+07
125969,A950250,테라뷰,2026-03-31,NaN,NaN,NaN,225537.59,NaN,NaN,NaN,NaN,NaN,NaN
125970,A950250,테라뷰,2026-06-04,NaN,NaN,NaN,125732.77,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
quarter_pivot.columns.name = None

In [66]:
quarter_pivot = quarter_pivot.sort_values(['코드', '코드명']).reset_index(drop= True)

In [67]:
quarter_pivot

,코드,코드명,날짜,당기순이익(천원),매출액(천원),부채총계(천원),시가총액(티커-상장예정주식수 포함)(백만원),영업이익(천원),영업활동으로인한현금흐름(천원),유동자산(천원),이익잉여금(천원),자본총계(천원),자산총계(천원),부채비율(%),유동비율_추정(%),영업손실,흑자도산위험,부채과다,유동성위험,부채과다_4Q연속
0,A000010,(주)신한은행,2014-03-31,425157000.0,3.266976e+09,2.218657e+11,NaN,533673000.0,-2.771267e+09,NaN,9.838993e+09,2.056530e+10,2.424310e+11,1078.835480,NaN,False,True,True,False,False
1,A000010,(주)신한은행,2014-06-30,416954000.0,3.703068e+09,2.259672e+11,NaN,509186000.0,1.194104e+09,NaN,1.022730e+10,1.989330e+10,2.458605e+11,1135.895871,NaN,False,False,True,False,False
2,A000010,(주)신한은행,2014-09-30,430192000.0,2.980610e+09,2.320100e+11,NaN,548536000.0,-8.306920e+08,NaN,1.064001e+10,2.040162e+10,2.524117e+11,1137.213570,NaN,False,True,True,False,False
3,A000010,(주)신한은행,2014-12-30,183350000.0,3.418039e+09,2.351694e+11,NaN,206001000.0,6.221510e+08,NaN,1.080557e+10,2.047690e+10,2.556463e+11,1148.462067,NaN,False,False,True,False,True
4,A000010,(주)신한은행,2015-03-31,390022000.0,3.257967e+09,2.407635e+11,NaN,468606000.0,-1.522832e+09,NaN,1.072814e+10,2.009479e+10,2.608583e+11,1198.138767,NaN,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125966,A950250,테라뷰,2025-06-30,-1463047.0,1.884841e+06,8.031245e+06,NaN,-1556428.0,-5.686100e+05,8219631.0,-1.174321e+08,1.266033e+06,9.297279e+06,634.363006,102.345664,True,False,True,False,False
125967,A950250,테라뷰,2025-09-30,-1284777.0,1.458068e+06,9.053882e+06,NaN,-1976867.0,-1.152912e+06,8012532.0,-1.212469e+08,6.901000e+03,9.060783e+06,131196.667150,88.498304,True,False,True,False,False
125968,A950250,테라뷰,2025-12-30,-3212680.0,2.409468e+06,9.700868e+06,267448.51,-2540414.0,-3.235584e+06,44608231.0,-1.309612e+08,3.587846e+07,4.557933e+07,27.038138,459.837522,True,False,False,False,False
125969,A950250,테라뷰,2026-03-31,NaN,NaN,NaN,225537.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False
125970,A950250,테라뷰,2026-06-04,NaN,NaN,NaN,125732.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False

In [68]:
#부채비율, 영업손실, 흑자도산, 유동성지표 계산
# 부채비율(%) = 부채총계(천원) / 자본총계(천원) *100
quarter_pivot['부채비율(%)'] = (quarter_pivot['부채총계(천원)']/quarter_pivot['자본총계(천원)']) * 100

In [69]:
# 유동비율(%) =  유동자산/유동부채 *100 -> 유동부채는 Dart 시스템에서 알수 있어
# 유동비율_추정 (%) = 유동자산 / 부채총계  * 100 

quarter_pivot['유동비율_추정(%)'] = quarter_pivot['유동자산(천원)']/quarter_pivot['부채총계(천원)'] * 100

In [70]:
# 영업손실 -> 영업이익 <0
quarter_pivot['영업손실'] = quarter_pivot['영업이익(천원)'] <0

In [71]:
# 흑자도산위험 = 영업활동으로인한현금흐름 <0 & 당기순이익 >0
quarter_pivot['흑자도산위험'] = (quarter_pivot['영업활동으로인한현금흐름(천원)'] < 0) & (quarter_pivot['당기순이익(천원)'] > 0)

In [72]:
# 부채과다
quarter_pivot['부채과다'] = quarter_pivot['부채비율(%)'] >= 200
# 유동성위험
quarter_pivot['유동성위험'] = quarter_pivot['유동비율_추정(%)'] < 50

In [73]:
quarter_pivot

,코드,코드명,날짜,당기순이익(천원),매출액(천원),부채총계(천원),시가총액(티커-상장예정주식수 포함)(백만원),영업이익(천원),영업활동으로인한현금흐름(천원),유동자산(천원),이익잉여금(천원),자본총계(천원),자산총계(천원),부채비율(%),유동비율_추정(%),영업손실,흑자도산위험,부채과다,유동성위험,부채과다_4Q연속
0,A000010,(주)신한은행,2014-03-31,425157000.0,3.266976e+09,2.218657e+11,NaN,533673000.0,-2.771267e+09,NaN,9.838993e+09,2.056530e+10,2.424310e+11,1078.835480,NaN,False,True,True,False,False
1,A000010,(주)신한은행,2014-06-30,416954000.0,3.703068e+09,2.259672e+11,NaN,509186000.0,1.194104e+09,NaN,1.022730e+10,1.989330e+10,2.458605e+11,1135.895871,NaN,False,False,True,False,False
2,A000010,(주)신한은행,2014-09-30,430192000.0,2.980610e+09,2.320100e+11,NaN,548536000.0,-8.306920e+08,NaN,1.064001e+10,2.040162e+10,2.524117e+11,1137.213570,NaN,False,True,True,False,False
3,A000010,(주)신한은행,2014-12-30,183350000.0,3.418039e+09,2.351694e+11,NaN,206001000.0,6.221510e+08,NaN,1.080557e+10,2.047690e+10,2.556463e+11,1148.462067,NaN,False,False,True,False,True
4,A000010,(주)신한은행,2015-03-31,390022000.0,3.257967e+09,2.407635e+11,NaN,468606000.0,-1.522832e+09,NaN,1.072814e+10,2.009479e+10,2.608583e+11,1198.138767,NaN,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125966,A950250,테라뷰,2025-06-30,-1463047.0,1.884841e+06,8.031245e+06,NaN,-1556428.0,-5.686100e+05,8219631.0,-1.174321e+08,1.266033e+06,9.297279e+06,634.363006,102.345664,True,False,True,False,False
125967,A950250,테라뷰,2025-09-30,-1284777.0,1.458068e+06,9.053882e+06,NaN,-1976867.0,-1.152912e+06,8012532.0,-1.212469e+08,6.901000e+03,9.060783e+06,131196.667150,88.498304,True,False,True,False,False
125968,A950250,테라뷰,2025-12-30,-3212680.0,2.409468e+06,9.700868e+06,267448.51,-2540414.0,-3.235584e+06,44608231.0,-1.309612e+08,3.587846e+07,4.557933e+07,27.038138,459.837522,True,False,False,False,False
125969,A950250,테라뷰,2026-03-31,NaN,NaN,NaN,225537.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False
125970,A950250,테라뷰,2026-06-04,NaN,NaN,NaN,125732.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False

In [ ]:
#quarter_pivot.sort_values(['코드', '날짜'])

,코드,코드명,날짜,당기순이익(천원),매출액(천원),부채총계(천원),시가총액(티커-상장예정주식수 포함)(백만원),영업이익(천원),영업활동으로인한현금흐름(천원),유동자산(천원),이익잉여금(천원),자본총계(천원),자산총계(천원),부채비율(%),유동비율_추정(%),영업손실,흑자도산위험,부채과다,유동성위험
0,A000010,(주)신한은행,2014-03-31,425157000.0,3.266976e+09,2.218657e+11,NaN,533673000.0,-2.771267e+09,NaN,9.838993e+09,2.056530e+10,2.424310e+11,1078.835480,NaN,False,True,True,False
1,A000010,(주)신한은행,2014-06-30,416954000.0,3.703068e+09,2.259672e+11,NaN,509186000.0,1.194104e+09,NaN,1.022730e+10,1.989330e+10,2.458605e+11,1135.895871,NaN,False,False,True,False
2,A000010,(주)신한은행,2014-09-30,430192000.0,2.980610e+09,2.320100e+11,NaN,548536000.0,-8.306920e+08,NaN,1.064001e+10,2.040162e+10,2.524117e+11,1137.213570,NaN,False,True,True,False
3,A000010,(주)신한은행,2014-12-30,183350000.0,3.418039e+09,2.351694e+11,NaN,206001000.0,6.221510e+08,NaN,1.080557e+10,2.047690e+10,2.556463e+11,1148.462067,NaN,False,False,True,False
4,A000010,(주)신한은행,2015-03-31,390022000.0,3.257967e+09,2.407635e+11,NaN,468606000.0,-1.522832e+09,NaN,1.072814e+10,2.009479e+10,2.608583e+11,1198.138767,NaN,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125966,A950250,테라뷰,2025-06-30,-1463047.0,1.884841e+06,8.031245e+06,NaN,-1556428.0,-5.686100e+05,8219631.0,-1.174321e+08,1.266033e+06,9.297279e+06,634.363006,102.345664,True,False,True,False
125967,A950250,테라뷰,2025-09-30,-1284777.0,1.458068e+06,9.053882e+06,NaN,-1976867.0,-1.152912e+06,8012532.0,-1.212469e+08,6.901000e+03,9.060783e+06,131196.667150,88.498304,True,False,True,False
125968,A950250,테라뷰,2025-12-30,-3212680.0,2.409468e+06,9.700868e+06,267448.51,-2540414.0,-3.235584e+06,44608231.0,-1.309612e+08,3.587846e+07,4.557933e+07,27.038138,459.837522,True,False,False,False
125969,A950250,테라뷰,2026-03-31,NaN,NaN,NaN,225537.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False
125970,A950250,테라뷰,2026-06-04,NaN,NaN,NaN,125732.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False

In [74]:
# 부실지표 연속성 체크
# 부채과다_4Qd연속
quarter_pivot['부채과다_4Q연속'] = (
    quarter_pivot.groupby('코드')['부채과다'].transform(lambda x : x.rolling(window=4, min_periods=4).sum()==4)
    )

In [75]:
quarter_pivot['영업손실_4Q연속'] = (
    quarter_pivot.groupby('코드')['영업손실'].transform(lambda x : x.rolling(window=4, min_periods=4).sum()==4)
)

In [ ]:
quarter_pivot['흑자도산_2Q연속'] = quarter_pivot.groupby('코드')['흑자도산위험'].transform(lambda x : x.rolling(window=2, min_periods=2).sum()==2)

In [77]:
quarter_pivot['유동성위험_2Q연속'] =(
    quarter_pivot.groupby('코드')['유동성위험'].transform(lambda x : x.rolling(window=2, min_periods=2).sum()==2)
)

In [78]:
quarter_pivot

,코드,코드명,날짜,당기순이익(천원),매출액(천원),부채총계(천원),시가총액(티커-상장예정주식수 포함)(백만원),영업이익(천원),영업활동으로인한현금흐름(천원),유동자산(천원),...,부채비율(%),유동비율_추정(%),영업손실,흑자도산위험,부채과다,유동성위험,부채과다_4Q연속,영업손실_4Q연속,흑자도산_2Q연속,유동성위험_2Q연속
0,A000010,(주)신한은행,2014-03-31,425157000.0,3.266976e+09,2.218657e+11,NaN,533673000.0,-2.771267e+09,NaN,...,1078.835480,NaN,False,True,True,False,False,False,False,False
1,A000010,(주)신한은행,2014-06-30,416954000.0,3.703068e+09,2.259672e+11,NaN,509186000.0,1.194104e+09,NaN,...,1135.895871,NaN,False,False,True,False,False,False,False,False
2,A000010,(주)신한은행,2014-09-30,430192000.0,2.980610e+09,2.320100e+11,NaN,548536000.0,-8.306920e+08,NaN,...,1137.213570,NaN,False,True,True,False,False,False,False,False
3,A000010,(주)신한은행,2014-12-30,183350000.0,3.418039e+09,2.351694e+11,NaN,206001000.0,6.221510e+08,NaN,...,1148.462067,NaN,False,False,True,False,True,False,False,False
4,A000010,(주)신한은행,2015-03-31,390022000.0,3.257967e+09,2.407635e+11,NaN,468606000.0,-1.522832e+09,NaN,...,1198.138767,NaN,False,True,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125966,A950250,테라뷰,2025-06-30,-1463047.0,1.884841e+06,8.031245e+06,NaN,-1556428.0,-5.686100e+05,8219631.0,...,634.363006,102.345664,True,False,True,False,False,False,False,False
125967,A950250,테라뷰,2025-09-30,-1284777.0,1.458068e+06,9.053882e+06,NaN,-1976867.0,-1.152912e+06,8012532.0,...,131196.667150,88.498304,True,False,True,False,False,False,False,False
125968,A950250,테라뷰,2025-12-30,-3212680.0,2.409468e+06,9.700868e+06,267448.51,-2540414.0,-3.235584e+06,44608231.0,...,27.038138,459.837522,True,False,False,False,False,False,False,False
125969,A950250,테라뷰,2026-03-31,NaN,NaN,NaN,225537.59,NaN,NaN,NaN,...,NaN,NaN,False,False,False,False,False,False,False,False
125970,A950250,테라뷰,2026-06-04,NaN,NaN,NaN,125732.77,NaN,NaN,NaN,...,NaN,NaN,False,False,False,False,False,False,False,False