In [1]:
import pandas as pd

In [4]:
df3 = pd.read_csv('./3. 2013년 이후 재무 데이터 (분기).csv')
df3

,코드,코드명,아이템명,2014-03-31 00:00:00,2014-06-30 00:00:00,2014-09-30 00:00:00,2014-12-30 00:00:00,2015-03-31 00:00:00,2015-06-30 00:00:00,2015-09-30 00:00:00,...,2024-03-29 00:00:00,2024-06-28 00:00:00,2024-09-30 00:00:00,2024-12-30 00:00:00,2025-03-31 00:00:00,2025-06-30 00:00:00,2025-09-30 00:00:00,2025-12-30 00:00:00,2026-03-31 00:00:00,2026-06-04 00:00:00
0,A005930,삼성전자,매출액(천원),5.367533e+10,5.235323e+10,4.744731e+10,5.273012e+10,4.711792e+10,4.853754e+10,5.168257e+10,...,7.191560e+10,7.406830e+10,7.909873e+10,7.578827e+10,7.914050e+10,7.456632e+10,8.606175e+10,9.383737e+10,1.338734e+11,NaN
1,A005930,삼성전자,영업이익(천원),8.488799e+09,7.187323e+09,4.060522e+09,5.288427e+09,5.979367e+09,6.897937e+09,7.393373e+09,...,6.606009e+09,1.044388e+10,9.183371e+09,6.492703e+09,6.685272e+09,4.676057e+09,1.216606e+10,2.007366e+10,5.723280e+10,NaN
2,A005930,삼성전자,세전계속사업이익(천원),9.648970e+09,7.785106e+09,4.846871e+09,5.594087e+09,6.218643e+09,7.628024e+09,7.390119e+09,...,7.706723e+09,1.159534e+10,1.032041e+10,7.907255e+09,9.151576e+09,5.756129e+09,1.354556e+10,2.102820e+10,5.882843e+10,NaN
3,A005930,삼성전자,당기순이익(지배)(천원),7.484680e+09,6.176506e+09,4.135422e+09,5.285891e+09,4.519323e+09,5.626734e+09,5.306104e+09,...,6.621030e+09,9.642653e+09,9.781547e+09,7.576133e+09,8.028407e+09,4.934034e+09,1.200646e+10,1.929205e+10,4.710119e+10,NaN
4,A005930,삼성전자,당기순이익(비지배)(천원),8.976100e+07,7.427500e+07,8.692300e+07,6.090000e+07,1.064920e+08,1.255630e+08,1.524550e+08,...,1.336780e+08,1.986920e+08,3.193570e+08,1.782610e+08,1.944710e+08,1.824010e+08,2.192860e+08,3.496910e+08,1.240820e+08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132272,A495900,에이엠시지,외국인지분율(%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN
132273,A495900,에이엠시지,총현금흐름(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132274,A495900,에이엠시지,CAPEX(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132275,A495900,에이엠시지,기초현금(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132276,A495900,에이엠시지,기말현금(천원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# wide -> long format transformation

data_columns = df3.columns[3:]
data_columns

Index(['2014-03-31 00:00:00', '2014-06-30 00:00:00', '2014-09-30 00:00:00',
       '2014-12-30 00:00:00', '2015-03-31 00:00:00', '2015-06-30 00:00:00',
       '2015-09-30 00:00:00', '2015-12-30 00:00:00', '2016-03-31 00:00:00',
       '2016-06-30 00:00:00', '2016-09-30 00:00:00', '2016-12-29 00:00:00',
       '2017-03-31 00:00:00', '2017-06-30 00:00:00', '2017-09-29 00:00:00',
       '2017-12-28 00:00:00', '2018-03-30 00:00:00', '2018-06-29 00:00:00',
       '2018-09-28 00:00:00', '2018-12-28 00:00:00', '2019-03-29 00:00:00',
       '2019-06-28 00:00:00', '2019-09-30 00:00:00', '2019-12-30 00:00:00',
       '2020-03-31 00:00:00', '2020-06-30 00:00:00', '2020-09-29 00:00:00',
       '2020-12-30 00:00:00', '2021-03-31 00:00:00', '2021-06-30 00:00:00',
       '2021-09-30 00:00:00', '2021-12-30 00:00:00', '2022-03-31 00:00:00',
       '2022-06-30 00:00:00', '2022-09-30 00:00:00', '2022-12-29 00:00:00',
       '2023-03-31 00:00:00', '2023-06-30 00:00:00', '2023-09-27 00:00:00',
       '2023-12-28 00:00:00', '2024-03-29 00:00:00', '2024-06-28 00:00:00',
       '2024-09-30 00:00:00', '2024-12-30 00:00:00', '2025-03-31 00:00:00',
       '2025-06-30 00:00:00', '2025-09-30 00:00:00', '2025-12-30 00:00:00',
       '2026-03-31 00:00:00', '2026-06-04 00:00:00'],
      dtype='str')

In [7]:
date_columns = df3.columns[3:]  # 코드, 코드명, 아이템명 제외

df_long = df3.melt(
    id_vars=['코드', '코드명', '아이템명'],
    value_vars=date_columns,
    var_name='날짜',
    value_name='값'
)
df_long['날짜'] = pd.to_datetime(df_long['날짜'])
df_long['연도'] = df_long['날짜'].dt.year
df_long['값'] = pd.to_numeric(df_long['값'], errors='coerce')

In [8]:
df_long

              코드    코드명            아이템명         날짜             값    연도
0        A005930   삼성전자         매출액(천원) 2014-03-31  5.367533e+10  2014
1        A005930   삼성전자        영업이익(천원) 2014-03-31  8.488799e+09  2014
2        A005930   삼성전자    세전계속사업이익(천원) 2014-03-31  9.648970e+09  2014
3        A005930   삼성전자   당기순이익(지배)(천원) 2014-03-31  7.484680e+09  2014
4        A005930   삼성전자  당기순이익(비지배)(천원) 2014-03-31  8.976100e+07  2014
...          ...    ...             ...        ...           ...   ...
6613845  A495900  에이엠시지       외국인지분율(%) 2026-06-04           NaN  2026
6613846  A495900  에이엠시지       총현금흐름(천원) 2026-06-04           NaN  2026
6613847  A495900  에이엠시지       CAPEX(천원) 2026-06-04           NaN  2026
6613848  A495900  에이엠시지        기초현금(천원) 2026-06-04           NaN  2026
6613849  A495900  에이엠시지        기말현금(천원) 2026-06-04           NaN  2026

[6613850 rows x 6 columns]